"""Department-aware assessment question bank (FRAC-flavoured).

Distractor design rules (anti-guessability):
  - all four options have similar length (no "longest option is correct")
  - all options share the same grammatical structure and level of detail
  - the correct-answer position is distributed evenly across A/B/C/D
Questions are grouped by competency type (Domain / Functional / Behavioural),
tagged L1 (easy) / L2 (medium) / L3 (hard), and served based on the logged-in
user's department (keyword matching with a generic fallback).
"""

QUESTION_BANK = {
    "space": [
        # ---- L1 (easy) ----
        {"id": "spc1", "level": "L1", "qtype": "Domain", "area": "Remote Sensing Fundamentals",
         "text": "Which type of satellite orbit allows continuous observation of the same area of the Earth?",
         "options": ["A polar sun-synchronous orbit at low altitude",
                     "A low Earth equatorial orbit with repeating tracks",
                     "A geostationary orbit fixed above the equator",
                     "A highly elliptical Molniya orbit over high latitudes"], "answer": 2},
        {"id": "spc2", "level": "L1", "qtype": "Domain", "area": "Remote Sensing Fundamentals",
         "text": "In optical remote sensing, the Normalized Difference Vegetation Index (NDVI) primarily indicates:",
         "options": ["Depth of soil moisture beneath the surface layer",
                     "Temperature variation across the observed land surface",
                     "Salinity levels in coastal and inland water bodies",
                     "Greenness and density of living vegetation cover"], "answer": 3},
        {"id": "spc3", "level": "L1", "qtype": "Domain", "area": "Remote Sensing Fundamentals",
         "text": "Which sensor type can image the Earth's surface at night and through clouds?",
         "options": ["Optical multispectral sensors relying on reflected sunlight",
                     "Thermal infrared sensors measuring emitted surface heat",
                     "Synthetic Aperture Radar transmitting microwave pulses",
                     "Hyperspectral sensors recording hundreds of narrow bands"], "answer": 2},
        {"id": "spc4", "level": "L1", "qtype": "Domain", "area": "Satellite Data Processing",
         "text": "Georeferencing a satellite image means:",
         "options": ["Compressing image pixels for efficient satellite storage",
                     "Enhancing image resolution through resampling techniques",
                     "Detecting and removing cloud cover from the scene",
                     "Assigning real-world map coordinates to image pixels"], "answer": 3},
        {"id": "spc5", "level": "L1", "qtype": "Functional", "area": "GIS",
         "text": "A vector GIS layer differs from a raster layer in that it stores features as:",
         "options": ["Points, lines and polygons carrying attribute tables",
                     "A regular grid of uniformly sized pixels with values",
                     "Frequency bands spanning the electromagnetic spectrum",
                     "Compressed video frames in geospatial storage formats"], "answer": 0},
        {"id": "spc6", "level": "L1", "qtype": "Functional", "area": "Data Interpretation",
         "text": "Time-series analysis of NDVI over a district is best used to:",
         "options": ["Track crop health and drought stress across seasons",
                     "Design satellite hardware for long-duration missions",
                     "Replace all ground-based agricultural surveys entirely",
                     "Estimate district population from vegetation patterns"], "answer": 0},
        {"id": "spc7", "level": "L1", "qtype": "Functional", "area": "Digital Governance",
         "text": "The Bhuvan geoportal of ISRO is an example of:",
         "options": ["A communications satellite operated by ISRO",
                     "A weather balloon programme for atmospheric research",
                     "A reusable launch vehicle under development at ISRO",
                     "A national geospatial platform for public map services"], "answer": 3},
        {"id": "spc8", "level": "L1", "qtype": "Functional", "area": "Cybersecurity and Data Protection",
         "text": "Satellite imagery classified for restricted government use should be:",
         "options": ["Handled strictly per government security classification rules",
                     "Shared freely on public cloud drives for transparency",
                     "Posted on official social media to build public trust",
                     "Forwarded to personal email accounts for safe keeping"], "answer": 0},
        {"id": "spc9", "level": "L1", "qtype": "Behavioural", "area": "Communication",
         "text": "Explaining satellite-based flood-inundation maps to district officials, you should:",
         "options": ["Use technical radar terminology to explain map details",
                     "Present clear maps with legends and actionable next steps",
                     "Share only raw data files without any interpretation",
                     "Withhold all maps until higher headquarters approves"], "answer": 1},
        # ---- L2 (medium) ----
        {"id": "spc10", "level": "L2", "qtype": "Domain", "area": "Remote Sensing Fundamentals",
         "text": "A sun-synchronous polar orbit is preferred for Earth-observation satellites mainly because it:",
         "options": ["Keeps the satellite fixed over a single ground point",
                     "Completely avoids the Van Allen radiation belts",
                     "Requires no orbital station-keeping manoeuvres",
                     "Crosses each location at the same local solar time"], "answer": 3},
        {"id": "spc11", "level": "L2", "qtype": "Domain", "area": "Remote Sensing Fundamentals",
         "text": "Vegetation appears bright in near-infrared imagery primarily because of:",
         "options": ["Strong thermal emission from leaves in the NIR range",
                     "High water content in stems scattering NIR radiation",
                     "Chlorophyll absorbing visible light while leaf structure reflects NIR",
                     "A bright soil background dominating the NIR signal"], "answer": 2},
        {"id": "spc12", "level": "L2", "qtype": "Domain", "area": "Satellite Data Processing",
         "text": "The spatial resolution of a sensor refers to:",
         "options": ["The number of spectral bands the sensor records",
                     "How frequently the sensor revisits the same location",
                     "The smallest ground feature the sensor can distinguish",
                     "The radiometric accuracy of recorded brightness values"], "answer": 2},
        {"id": "spc13", "level": "L2", "qtype": "Domain", "area": "Satellite Data Processing",
         "text": "Atmospheric correction of optical imagery is performed to:",
         "options": ["Remove cloud shadows from the satellite scene",
                     "Convert top-of-atmosphere reflectance to surface reflectance",
                     "Sharpen image edges for clearer visual interpretation",
                     "Reduce file size for faster transmission to ground"], "answer": 1},
        {"id": "spc14", "level": "L2", "qtype": "Functional", "area": "GIS",
         "text": "An overlay analysis combining a flood-prone-area layer with a settlement layer is used to:",
         "options": ["Identify settlements located within flood-prone zones",
                     "Classify land cover types from raw satellite pixels",
                     "Georeference scanned historical survey maps accurately",
                     "Compress large map layers for web-based visualisation"], "answer": 0},
        {"id": "spc15", "level": "L2", "qtype": "Functional", "area": "GIS",
         "text": "Which coordinate reference system is most appropriate for nationwide Indian mapping projects today?",
         "options": ["Latitude-longitude on the century-old Everest datum alone",
                     "Local plane survey coordinates used uniformly across India",
                     "Projection-based systems conforming to NSDI national standards",
                     "Coordinate systems chosen independently by each agency"], "answer": 2},
        {"id": "spc16", "level": "L2", "qtype": "Functional", "area": "Python",
         "text": "Which Python library is most commonly used for reading and analysing raster geospatial data?",
         "options": ["Matplotlib, for publication-quality statistical charts",
                     "BeautifulSoup, for parsing HTML pages from the web",
                     "Seaborn, for statistical data visualisation plots",
                     "Rasterio and GDAL, for reading and writing geospatial rasters"], "answer": 3},
        {"id": "spc17", "level": "L2", "qtype": "Functional", "area": "Data Interpretation",
         "text": "A change-detection study shows urban area expansion of 12% over a decade. The most defensible first step before reporting is:",
         "options": ["Publish the finding immediately through a press release",
                     "Validate against independent data and report accuracy first",
                     "Round the estimate down to avoid overstating the change",
                     "Report only the year showing the maximum observed change"], "answer": 1},
        {"id": "spc18", "level": "L2", "qtype": "Behavioural", "area": "Problem Solving",
         "text": "Cloud cover blocks optical imagery during a flood. The most practical response is to:",
         "options": ["Abandon the flood assessment until conditions improve",
                     "Wait indefinitely for a completely clear weather window",
                     "Reuse imagery from the same season of the previous decade",
                     "Switch to Synthetic Aperture Radar or temporal composites"], "answer": 3},
        # ---- L3 (hard) ----
        {"id": "spc19", "level": "L3", "qtype": "Domain", "area": "Satellite Data Processing",
         "text": "In SAR interferometry (InSAR), millimetre-scale ground deformation is estimated from:",
         "options": ["Differences in backscatter intensity between passes",
                     "Phase differences between successive radar acquisitions",
                     "Ratios of polarisation channels of the same acquisition",
                     "Thermal anomalies detected between observation dates"], "answer": 1},
        {"id": "spc20", "level": "L3", "qtype": "Domain", "area": "Remote Sensing Fundamentals",
         "text": "A key limitation of using NDVI for crop-yield estimation in heterogeneous smallholder landscapes is:",
         "options": ["NDVI cannot be computed from satellite observations at all",
                     "Mixed pixels confuse crop signals with background variability",
                     "NDVI works only at night for irrigated farmland areas",
                     "NDVI requires active radar illumination to function properly"], "answer": 1},
        {"id": "spc21", "level": "L3", "qtype": "Domain", "area": "Satellite Data Processing",
         "text": "Speckle noise inherent in SAR imagery is best mitigated by:",
         "options": ["Multi-looking and adaptive filters such as the Lee filter",
                     "Nearest-neighbour resampling of the raw radar image",
                     "Histogram equalisation of the amplitude image",
                     "Doubling the pixel grid through image interpolation"], "answer": 0},
        {"id": "spc22", "level": "L3", "qtype": "Functional", "area": "GIS",
         "text": "For hydrological flood-inundation modelling, a Digital Elevation Model is used primarily to derive:",
         "options": ["Land ownership parcels for compensation claim records",
                     "Soil chemistry properties across the catchment area",
                     "Flow direction and accumulation for inundation extents",
                     "Population density estimates in the affected districts"], "answer": 2},
        {"id": "spc23", "level": "L3", "qtype": "Functional", "area": "AI and Emerging Tech",
         "text": "When applying deep-learning semantic segmentation to satellite imagery, the most defensible way to report accuracy is:",
         "options": ["Training accuracy alone, computed on the labelled dataset",
                     "Confusion-matrix metrics on a spatially independent test set",
                     "One analyst's visual impression of the output map",
                     "Pixel counts of each predicted class within the scene"], "answer": 1},
        {"id": "spc24", "level": "L3", "qtype": "Functional", "area": "Python",
         "text": "For processing a 50,000 x 50,000 pixel national mosaic that exceeds RAM, the most appropriate approach is:",
         "options": ["Loading the entire mosaic into one large NumPy array",
                     "Windowed block processing with rasterio windows or Dask",
                     "Converting the mosaic into comma-separated text files",
                     "Permanently downsampling to a small overview image"], "answer": 1},
        {"id": "spc25", "level": "L3", "qtype": "Behavioural", "area": "Decision Making",
         "text": "Two satellite-derived estimates of cropped area differ by 8%. As the approving officer you should:",
         "options": ["Choose the estimate derived from the newer satellite",
                     "Average the two estimates and publish the combined figure",
                     "Commission a validation protocol comparing methods and errors",
                     "Withhold both estimates from every user indefinitely"], "answer": 2},
    ],
    "statistics": [
        {"id": "stat1", "level": "L2", "qtype": "Domain", "area": "Sampling Techniques",
         "text": "A survey must estimate the average household expenditure in a large state with wide urban–rural variation. Which sampling design is most appropriate?",
         "options": ["Simple random sampling of households across the whole state",
                     "Systematic sampling with a random start from voter lists",
                     "Stratified sampling with separate urban and rural strata",
                     "Snowball sampling through local community organisations"], "answer": 2},
        {"id": "stat2", "level": "L2", "qtype": "Domain", "area": "Survey Design",
         "text": "In the Official Statistical System, what is the primary purpose of a 'pilot round' before a full survey launch?",
         "options": ["Publishing preliminary estimates before the full survey",
                     "Testing the questionnaire, field logistics and training",
                     "Meeting administrative approval requirements quickly",
                     "Replacing the census in years between census cycles"], "answer": 1},
        {"id": "stat3", "level": "L2", "qtype": "Domain", "area": "Statistical Methods",
         "text": "The Consumer Price Index (CPI) is an example of:",
         "options": ["An index number tracking price changes over time",
                     "A measure of central tendency of household spending",
                     "A sampling frame for consumer expenditure surveys",
                     "A regression coefficient used in demand analysis"], "answer": 0},
        {"id": "stat4", "level": "L3", "qtype": "Functional", "area": "Data Interpretation",
         "text": "A district's NSDP per capita is rising, but its Gini coefficient is also rising. What does this combination suggest?",
         "options": ["Uniform income growth across all population groups",
                     "A decline in average household income overall",
                     "A systematic error in the national accounts data",
                     "Rising average incomes alongside widening inequality"], "answer": 3},
        {"id": "stat5", "level": "L2", "qtype": "Functional", "area": "Python",
         "text": "In pandas, which function is most direct for computing a mean by category?",
         "options": ["df.sort_values(), to order rows by a chosen column",
                     "df.groupby(col).mean(), to aggregate values by category",
                     "df.pivot(), to reshape between long and wide forms",
                     "df.applymap(), to transform every cell individually"], "answer": 1},
        {"id": "stat6", "level": "L2", "qtype": "Functional", "area": "SQL",
         "text": "Which SQL clause filters rows AFTER grouping has been applied?",
         "options": ["WHERE, which filters rows before any grouping occurs",
                     "ORDER BY, which sorts the final result set rows",
                     "HAVING, which filters aggregated groups after grouping",
                     "LIMIT, which restricts the number of returned rows"], "answer": 2},
        {"id": "stat7", "level": "L2", "qtype": "Functional", "area": "Digital Governance",
         "text": "The 'once-only' principle in digital government means:",
         "options": ["Citizens submit data once, reused across departments",
                     "Each scheme accepts exactly one application per person",
                     "Data is stored a single time for security reasons",
                     "One officer alone signs off on every file decision"], "answer": 0},
        {"id": "stat8", "level": "L3", "qtype": "Functional", "area": "Cybersecurity and Data Protection",
         "text": "Under the DPDP Act, 2023, before processing personal data a government body must generally ensure:",
         "options": ["Data is published openly on government portals",
                     "Lawful basis plus notice and consent requirements are met",
                     "Records are retained for a minimum of ten years",
                     "Parliament grants explicit consent for each dataset"], "answer": 1},
        {"id": "stat9", "level": "L2", "qtype": "Behavioural", "area": "Communication",
         "text": "You must present complex survey findings to non-technical senior leadership. The best first step is:",
         "options": ["Share the complete raw dataset with all respondents",
                     "Present the full methodology in technical detail first",
                     "Circulate the survey questionnaire among the leaders",
                     "Lead with key findings in plain language and few charts"], "answer": 3},
        {"id": "stat10", "level": "L3", "qtype": "Behavioural", "area": "Ethics and Values",
         "text": "A stakeholder pressures you to delay releasing an unfavourable statistic indefinitely. The appropriate action is to:",
         "options": ["Delay the release indefinitely on the stakeholder's advice",
                     "Modify the estimates slightly before releasing them",
                     "Follow the dissemination policy and escalate through channels",
                     "Share the figures informally with trusted media contacts"], "answer": 2},
    ],
    "general": [
        {"id": "gen1", "level": "L1", "qtype": "Domain", "area": "National Priorities",
         "text": "Viksit Bharat 2047 envisions India as a developed nation by which year?",
         "options": ["By the year 2022", "By the year 2030", "By the year 2047", "By the year 2050"], "answer": 2},
        {"id": "gen2", "level": "L2", "qtype": "Functional", "area": "Digital Governance",
         "text": "Which initiative provides trusted digital document storage and access for government services?",
         "options": ["DigiLocker, for tamper-proof digital documents",
                     "Digital India, the umbrella e-services programme",
                     "Ayushman Bharat, the national health protection scheme",
                     "SWAYAM, the platform for online course certification"], "answer": 0},
        {"id": "gen3", "level": "L2", "qtype": "Functional", "area": "AI and Emerging Tech",
         "text": "A key risk of using generative AI for official drafting without review is:",
         "options": ["It is always slower than manual drafting work",
                     "Confidently presented content that may be incorrect",
                     "Inability to process Indian languages and scripts",
                     "Requirement for special electrical infrastructure"], "answer": 1},
        {"id": "gen4", "level": "L1", "qtype": "Behavioural", "area": "Citizen Centricity",
         "text": "'Jan Bhagidari' in governance best refers to:",
         "options": ["Privatisation of public service delivery agencies",
                     "Judicial review of executive administrative actions",
                     "Public participation in planning and service delivery",
                     "Inter-ministerial coordination on policy matters"], "answer": 2},
        {"id": "gen5", "level": "L2", "qtype": "Behavioural", "area": "Decision Making",
         "text": "The 'rule-based to role-based' vision of Mission Karmayogi emphasises:",
         "options": ["Strict seniority-based posting of civil servants",
                     "Outsourcing of government roles to private vendors",
                     "Reducing the total sanctioned workforce strength",
                     "Competency-driven role assignment and capacity building"], "answer": 3},
        {"id": "gen6", "level": "L2", "qtype": "Functional", "area": "Policy Formulation",
         "text": "Evidence-based policy making primarily relies on:",
         "options": ["Tradition and administrative precedent alone",
                     "Data, evaluation studies and stakeholder evidence",
                     "Media opinion polls and trending public sentiment",
                     "The individual intuition of senior decision makers"], "answer": 1},
    ],
}

DEPARTMENT_KEYWORDS = {
    "statistics": ["statistic", "mospi", "nso", "survey", "census"],
    "space": ["space", "isro", "adrin", "satellite"],
    # departments can be added here; everything else falls back to "general"
}


def department_key(department: str) -> str:
    d = (department or "").lower()
    for key, words in DEPARTMENT_KEYWORDS.items():
        if any(w in d for w in words):
            return key
    return "general"


def questions_for(department: str) -> list:
    return QUESTION_BANK[department_key(department)]
